# Generated by Django 6.0.2 on 2026-03-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Джинси', 'Джинси'), ('Сорочки', 'Сорочки'), ('Костюми', 'Костюми'), ('Спорт', 'Спорт'), ('Куртки', 'Куртки'), ('Кросівки', 'Кросівки')], max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('old_price', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('emoji', models.CharField(default='👔', max_length=10)),
                ('sizes', models.JSONField(default=list)),
                ('details', models.JSONField(blank=True, default=dict, help_text='{"Склад":"...", "Країна":"...", "Колір":"..."}')),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('in_stock', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['-created_at'],
            },
        ),
    ]
